/*******************************************************************************
 Copyright (c) 2016 Lumen Labs (HK) Limited. All Rights Reserved.
*******************************************************************************/

#include "LL_LED_Panel_WS2812.h"

//custom color card
#define LL_COLOR_TYPE_NUM  8
#define LL_COLOR_BRIGHTNESS_LEVEL 6
static const unsigned long Animation_Custom_Color_Disk[LL_COLOR_TYPE_NUM][LL_COLOR_BRIGHTNESS_LEVEL] ={
{WS2812_COLOR_WHITE_40, WS2812_COLOR_WHITE_50, WS2812_COLOR_WHITE_60, WS2812_COLOR_WHITE_70, WS2812_COLOR_WHITE, WS2812_COLOR_WHITE_100}, //white
{WS2812_COLOR_RED_40, WS2812_COLOR_RED_50, WS2812_COLOR_RED_60, WS2812_COLOR_RED_70, WS2812_COLOR_RED_80, WS2812_COLOR_RED_100}, //red
{WS2812_COLOR_PURPLE_40, WS2812_COLOR_PURPLE_50, WS2812_COLOR_PURPLE_60, WS2812_COLOR_PURPLE_70, WS2812_COLOR_PURPLE_80, WS2812_COLOR_PURPLE_100}, //purple
{WS2812_COLOR_BLUE_GREEN_40, WS2812_COLOR_BLUE_GREEN_50, WS2812_COLOR_BLUE_GREEN_60, WS2812_COLOR_BLUE_GREEN_70, WS2812_COLOR_BLUE_GREEN_80, WS2812_COLOR_BLUE_GREEN_100}, //blue-green
{WS2812_COLOR_PINK_40, WS2812_COLOR_PINK_50, WS2812_COLOR_PINK_60, WS2812_COLOR_PINK_70, WS2812_COLOR_PINK_80, WS2812_COLOR_PINK_100}, //pink
{WS2812_COLOR_YELLOW_GREEN_40, WS2812_COLOR_YELLOW_GREEN_50, WS2812_COLOR_YELLOW_GREEN_60, WS2812_COLOR_YELLOW_GREEN_70, WS2812_COLOR_YELLOW_GREEN_80,  WS2812_COLOR_YELLOW_GREEN_100}, //yellow-green
{WS2812_COLOR_BLUE_40, WS2812_COLOR_BLUE_50, WS2812_COLOR_BLUE_60, WS2812_COLOR_BLUE_70, WS2812_COLOR_BLUE_80, WS2812_COLOR_BLUE_100}, //blue
{WS2812_COLOR_ORANGE_40, WS2812_COLOR_ORANGE_50, WS2812_COLOR_ORANGE_60, WS2812_COLOR_ORANGE_70, WS2812_COLOR_ORANGE_80, WS2812_COLOR_ORANGE_100}, //orange
};
    
//Slow flash 
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_SlowFlash_Front[] = {
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},  
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_SlowFlash_Rear[] = {
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};

//Fast flash
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_FastFlash_Front[] = {
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_FastFlash_Rear[] = {
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};

//Solid Mode
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_SolidMode_Front[] = {
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_SolidMode_Rear[] = {
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
};

//Pairing Mode
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PairingMode_Front[] = {
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PairingMode_Rear[] = {
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_WHITE,DEFAULT_WHITE,}},
};

//Power On Level 1 Front
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_1_Front[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,}},
{{0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
}; 

//Power On Level 2 Front
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_2_Front[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,}},
}; 

//Power On Level 3 Front
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_3_Front[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,}},
}; 

//Power On Level 4 Front
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_4_Front[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN}},
};

//Power On Level 1 Rear
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_1_Rear[] = {
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
};

//Power On Level 2 Rear
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_2_Rear[] = {
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
};

//Power On Level 3 Rear
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_3_Rear[] = {
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
};
   
//Power On Level 4 Rear
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOn_Level_4_Rear[] = {
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{0,0,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
{{DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,DEFAULT_GREEN,}},
};


static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOnShowBattery[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,DEFAULT_ORANGE,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_PowerOff[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_HalfBlink_Front[] = {
{{DEFAULT_WHITE,0,0,0,DEFAULT_WHITE,0,0,0,DEFAULT_WHITE,0,0,0,DEFAULT_WHITE,0,0,DEFAULT_WHITE,0,0,0,DEFAULT_WHITE,0,0,0,DEFAULT_WHITE,0,0,0,DEFAULT_WHITE,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_HalfBlink_Rear[] = {
{{DEFAULT_RED,0,0,0,DEFAULT_RED,0,0,0,DEFAULT_RED,0,0,0,DEFAULT_RED,0,0,DEFAULT_RED,0,0,0,DEFAULT_RED,0,0,0,DEFAULT_RED,0,0,0,DEFAULT_RED,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
};    

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_DoubleWave_Front[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,0,0,0,0,}},
{{0,0,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,0,0,}},
{{0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,}},
{{0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,}},
{{0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,}},
{{0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,}},
{{0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,DEFAULT_WHITE,0,}},
{{0,DEFAULT_WHITE,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,DEFAULT_WHITE,0,}},
{{0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};


static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_DoubleWave_Rear[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,0,0,0,0,}},
{{0,0,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,0,0,}},
{{0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,}},
{{0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,}},
{{0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,}},
{{0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,}},
{{0,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,DEFAULT_RED,0,}},
{{0,DEFAULT_RED,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,DEFAULT_RED,0,}},
{{0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};

//Alarm led
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Alarm[] = {
{{DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,DEFAULT_BLUE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};

//Charging
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Charging[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_1,POWERON_BLUE_1,POWERON_BLUE_1,POWERON_BLUE_1,POWERON_BLUE_1,POWERON_BLUE_1,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_2,POWERON_BLUE_2,POWERON_BLUE_2,POWERON_BLUE_2,POWERON_BLUE_2,POWERON_BLUE_2,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_3,POWERON_BLUE_3,POWERON_BLUE_3,POWERON_BLUE_3,POWERON_BLUE_3,POWERON_BLUE_3,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_4,POWERON_BLUE_4,POWERON_BLUE_4,POWERON_BLUE_4,POWERON_BLUE_4,POWERON_BLUE_4,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_5,POWERON_BLUE_5,POWERON_BLUE_5,POWERON_BLUE_5,POWERON_BLUE_5,POWERON_BLUE_5,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_6,POWERON_BLUE_6,POWERON_BLUE_6,POWERON_BLUE_6,POWERON_BLUE_6,POWERON_BLUE_6,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_7,POWERON_BLUE_7,POWERON_BLUE_7,POWERON_BLUE_7,POWERON_BLUE_7,POWERON_BLUE_7,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_8,POWERON_BLUE_8,POWERON_BLUE_8,POWERON_BLUE_8,POWERON_BLUE_8,POWERON_BLUE_8,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_9,POWERON_BLUE_9,POWERON_BLUE_9,POWERON_BLUE_9,POWERON_BLUE_9,POWERON_BLUE_9,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_10,POWERON_BLUE_10,POWERON_BLUE_10,POWERON_BLUE_10,POWERON_BLUE_10,POWERON_BLUE_10,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_11,POWERON_BLUE_11,POWERON_BLUE_11,POWERON_BLUE_11,POWERON_BLUE_11,POWERON_BLUE_11,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_12,POWERON_BLUE_12,POWERON_BLUE_12,POWERON_BLUE_12,POWERON_BLUE_12,POWERON_BLUE_12,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_13,POWERON_BLUE_13,POWERON_BLUE_13,POWERON_BLUE_13,POWERON_BLUE_13,POWERON_BLUE_13,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_14,POWERON_BLUE_14,POWERON_BLUE_14,POWERON_BLUE_14,POWERON_BLUE_14,POWERON_BLUE_14,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,POWERON_BLUE_15,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,}},
{{0,0,0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,0,0,}},
{{0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,}},
{{0,0,0,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,0,0,0,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
{{POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,POWERON_BLUE_16,}},
};

static T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Ricochet_Front[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,}},
{{0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,}},
{{0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,}},
{{0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,}},
{{0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,}},
{{0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_WHITE,DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,DEFAULT_WHITE,}},
{{DEFAULT_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_WHITE,}},
};

static T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Ricochet_Rear[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,}},
{{0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,}},
{{0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,}},
{{0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,}},
{{0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,}},
{{0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,}},
{{0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,}},
{{DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_RED,DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,DEFAULT_RED,}},
{{DEFAULT_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,DEFAULT_RED,}},
}; 

