/*******************************************************************************
 Copyright (c) 2016 Lumen Labs (HK) Limited. All Rights Reserved.
*******************************************************************************/

#include "LL_LED_Panel_WS2812.h"

// For the designers of animations to make this file:
// 1) Paste the data from the tool into each array like "static const T_FRAME__COLOR_CODE_FORMAT animationFrames_BeatingHeart[]", pls remember change the suffix like "BeatingHeart" to your own animation name.
//    Now this file has 11 array, just a demo, you can delete all of them and add your animations.
// 2) Register the animations in the last array "DemoAnimationTasks" by adding a line.
//    After you copy-paste a line, pls remember to change the names in the 1st and 3rd fields of the line, see the demo. (No need to know the meaning of every field of the line.)
// 3) Name this file as what you need, like "Bilal_Mar03.h".

//Turn left
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_TurnLeftSignal_Front[] = {
{{0,0,0,0,0,0,0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_TurnLeftSignal_Rear[] = {
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}}, 
};

//Turn right
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_TurnRightSignal_Front[] = {
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_TurnRightSignal_Rear[] = {
{{0,0,0,0,0,0,0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,TURNSIGNAL_ORANGE,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
};

//Brake signal
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_BrakeSignal_Front[] = {
{{MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,MAX_WHITE,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_BrakeSignal_Rear_Solid[] = {
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_BrakeSignal_Rear_SharpFlash[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,}},
{{MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,MAX_RED,}},
};

//Charging
static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Charging_Level_0[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Charging_Level_1[] = {
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},    
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
//{{0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
//{{0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,CHARGING_RED,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Charging_Level_2[] = {
{{0,0,0,0,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{CHARGING_ORANGE,CHARGING_ORANGE,0,0,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,CHARGING_ORANGE,CHARGING_ORANGE,0,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,CHARGING_ORANGE,CHARGING_ORANGE,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Charging_Level_3[] = {
{{0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{CHARGING_ORANGE,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{CHARGING_ORANGE,0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,CHARGING_ORANGE,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,CHARGING_ORANGE,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,CHARGING_ORANGE,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,CHARGING_ORANGE,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,CHARGING_ORANGE,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,CHARGING_ORANGE,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,CHARGING_ORANGE,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,CHARGING_ORANGE,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
{{0,0,0,0,0,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,CHARGING_ORANGE,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Charging_Level_4[] = {
{{0,0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{CHARGING_GREEN,0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{CHARGING_GREEN,0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,CHARGING_GREEN,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,CHARGING_GREEN,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,0,CHARGING_GREEN,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,0,CHARGING_GREEN,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
{{0,0,0,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
};

static const T_FRAME__COLOR_CODE_FORMAT AnimationFrame_Charging_Level_5[] = {
{{CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,CHARGING_GREEN,}},
};
